In [1]:
import pandas as pd

In [36]:
df = pd.read_csv('exp_data.csv')
df.drop('iteration', axis=1, inplace=True)
df

             program            dataset         time
0         kmeans_seq   kmeans_10000.txt     0.077539
1         kmeans_seq   kmeans_10000.txt     0.074086
2         kmeans_seq   kmeans_10000.txt     0.101857
3         kmeans_seq   kmeans_10000.txt     0.064126
4         kmeans_seq   kmeans_10000.txt     0.147441
..               ...                ...          ...
295  warshall_openmp  inputfile8000.txt  1892.710000
296  warshall_openmp  inputfile8000.txt  1896.250000
297  warshall_openmp  inputfile8000.txt  1890.930000
298  warshall_openmp  inputfile8000.txt  1888.970000
299  warshall_openmp  inputfile8000.txt  1877.440000

[300 rows x 3 columns]

In [43]:
df_avg = df.groupby(['program', 'dataset'], as_index=False).mean()
df_avg

            program                dataset         time
0          bfs_cuda   graph_g1000_s100.txt     0.413012
1          bfs_cuda  graph_g16000_s100.txt    15.641312
2          bfs_cuda   graph_g2000_s100.txt     0.613908
3          bfs_cuda   graph_g4000_s100.txt     1.325368
4          bfs_cuda   graph_g8000_s100.txt     3.843879
5        bfs_openmp   graph_g1000_s100.txt     3.658000
6        bfs_openmp  graph_g16000_s100.txt   776.734110
7        bfs_openmp   graph_g2000_s100.txt    13.068953
8        bfs_openmp   graph_g4000_s100.txt    49.467538
9        bfs_openmp   graph_g8000_s100.txt   193.846197
10          bfs_seq   graph_g1000_s100.txt     0.256332
11          bfs_seq  graph_g16000_s100.txt    56.769880
12          bfs_seq   graph_g2000_s100.txt     0.975686
13          bfs_seq   graph_g4000_s100.txt     3.616105
14          bfs_seq   graph_g8000_s100.txt    13.543446
15      kmeans_cuda       kmeans_10000.txt     0.333113
16      kmeans_cuda      kmeans_100000.txt     0.269787
17      kmeans_cuda     kmeans_1000000.txt     2.210920
18      kmeans_cuda    kmeans_10000000.txt    29.714816
19      kmeans_cuda     kmeans_5000000.txt    13.349164
20    kmeans_openmp       kmeans_10000.txt     1.146549
21    kmeans_openmp      kmeans_100000.txt    19.294884
22    kmeans_openmp     kmeans_1000000.txt   201.717079
23    kmeans_openmp    kmeans_10000000.txt  2470.457672
24    kmeans_openmp     kmeans_5000000.txt  1127.398192
25       kmeans_seq       kmeans_10000.txt     0.093010
26       kmeans_seq      kmeans_100000.txt     1.238965
27       kmeans_seq     kmeans_1000000.txt    19.304426
28       kmeans_seq    kmeans_10000000.txt   162.408275
29       kmeans_seq     kmeans_5000000.txt    93.431550
30     nqueens_cuda                     10    28.140000
31     nqueens_cuda                      6     0.180000
32     nqueens_cuda                      7     0.186000
33     nqueens_cuda                      8     0.218000
34     nqueens_cuda                      9     0.974000
35   nqueens_openmp                     10   140.305000
36   nqueens_openmp                      6     0.331253
37   nqueens_openmp                      7     0.338784
38   nqueens_openmp                      8     0.481344
39   nqueens_openmp                      9     5.131174
40      nqueens_seq                     10  2834.214000
41      nqueens_seq                      6     0.019831
42      nqueens_seq                      7     0.216381
43      nqueens_seq                      8     4.152784
44      nqueens_seq                      9    99.392720
45    warshall_cuda      inputfile1000.txt     0.496000
46    warshall_cuda      inputfile2000.txt     2.296000
47    warshall_cuda      inputfile4000.txt     9.146000
48    warshall_cuda       inputfile500.txt     0.116000
49    warshall_cuda      inputfile8000.txt    37.076000
50  warshall_openmp      inputfile1000.txt    10.140600
51  warshall_openmp      inputfile2000.txt    42.467560
52  warshall_openmp      inputfile4000.txt   264.118400
53  warshall_openmp       inputfile500.txt     3.928552
54  warshall_openmp      inputfile8000.txt  1889.260000
55     warshall_seq      inputfile1000.txt     4.038000
56     warshall_seq      inputfile2000.txt    31.720000
57     warshall_seq      inputfile4000.txt   251.450000
58     warshall_seq       inputfile500.txt     0.600000
59     warshall_seq      inputfile8000.txt  2004.262000

In [44]:
df_avg.to_csv('exp_data_avg.csv', index=False)